import { supabase } from './supabase'

/**
 * Inserta un pedido con sus líneas en Supabase.
 * @returns el pedido creado (fila de orders)
 */
export async function crearPedido({ userId, total, puntos, tienda, hora, items }) {
  // numero is generated by the DB sequence (orders_numero_seq)
  const { data: order, error: orderError } = await supabase
    .from('orders')
    .insert({
      user_id: userId,
      total,
      puntos,
      estado: 'pendiente',
      tienda_nombre: tienda.nombre,
      tienda_ciudad: tienda.ciudad,
      hora_recogida: hora,
    })
    .select()
    .single()

  if (orderError) throw orderError

  const lineas = items.map((item) => ({
    order_id: order.id,
    product_id: item.id,
    nombre: item.nombre,
    precio: item.precio,
    cantidad: item.qty,
    tamano: item.tamano || 'M',
    tipo_leche: item.tipo_leche || 'normal',
    extras: item.extras && item.extras.length > 0 ? JSON.stringify(item.extras) : '[]',
  }))

  const { error: itemsError } = await supabase
    .from('order_items')
    .insert(lineas)

  if (itemsError) throw itemsError

  return order
}

/**
 * Devuelve los pedidos del usuario autenticado (RLS filtra por user_id),
 * más recientes primero, con sus líneas anidadas.
 */
export async function listarPedidos() {
  const { data, error } = await supabase
    .from('orders')
    .select('*, order_items ( product_id, nombre, precio, cantidad )')
    .order('created_at', { ascending: false })

  if (error) throw error
  return data
}

/**
 * Devuelve la suma de puntos de todos los pedidos del usuario (RLS filtra).
 */
export async function calcularPuntos() {
  const { data, error } = await supabase
    .from('orders')
    .select('puntos')

  if (error) throw error
  return data.reduce((sum, row) => sum + row.puntos, 0)
}

// ── Admin functions (RLS admin policies required) ──

/**
 * Lists all orders (admin). RLS policy allows admins to see everything.
 */
export async function listarTodosPedidos(filtroEstado) {
  let query = supabase
    .from('orders')
    .select('*, order_items ( product_id, nombre, precio, cantidad )')
    .order('created_at', { ascending: false })

  if (filtroEstado) {
    query = query.eq('estado', filtroEstado)
  }

  const { data, error } = await query
  if (error) throw error
  return data
}

/**
 * Updates order status (admin).
 */
export async function actualizarEstadoPedido(orderId, nuevoEstado) {
  const { data, error } = await supabase
    .from('orders')
    .update({ estado: nuevoEstado })
    .eq('id', orderId)
    .select()
    .single()

  if (error) throw error
  return data
}

/**
 * Find active orders for a given user (pendiente or completado).
 */
export async function buscarPedidosActivos(userId) {
  const { data, error } = await supabase
    .from('orders')
    .select('*, order_items ( product_id, nombre, precio, cantidad )')
    .eq('user_id', userId)
    .in('estado', ['pendiente', 'completado'])
    .order('created_at', { ascending: false })

  if (error) throw error
  return data || []
}

/**
 * Fetch a user's profile by ID (admin use).
 * Uses maybeSingle to avoid 406 when RLS blocks the row.
 */
export async function buscarPerfil(userId) {
  console.log('[buscarPerfil] Buscando userId:', userId)
  const { data, error, status } = await supabase
    .from('profiles')
    .select('id, email, name, points, tier')
    .eq('id', userId)
    .maybeSingle()

  console.log('[buscarPerfil] status:', status, 'error:', error, 'data:', data)

  if (error) throw error
  if (!data) throw new Error(`Perfil no encontrado para ID: ${userId}. Status HTTP: ${status}`)
  return data
}
